### ISSUE TITLE
Capitalization code applies to postcodes where it should not.

### ISSUE THREAD

**Issue by tom-bell** [bournemouth/buildings-api#5]
@adamcooke Without having a lookup table for excluded values I don't know how we can get round this.

**Comment by adamcooke** [comment]
Well that's rubbish and a valid point! We could either exclude post codes by excluding data which matches something like `^[A-Z]{2}\d{1,2} ?\d[A-Z]{2}$` or just remove the prettyfication entirely.

The regex for postcode will only work well for basic/local post codes. London has some very odd post code formats.

**Comment by tom-bell** [comment]
Closing issue as no longer relevant!
